apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/test"
          name: test
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: test-dynamic-volume-claim